# Generated by Django 5.1.5 on 2025-01-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='company_bs',
            field=models.CharField(max_length=100),
        ),
    ]
